// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0
// source: proto/hello/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greeter_SayHello_FullMethodName      = "/hello.Greeter/SayHello"
	Greeter_SearchOrders_FullMethodName  = "/hello.Greeter/searchOrders"
	Greeter_UpdateOrders_FullMethodName  = "/hello.Greeter/updateOrders"
	Greeter_ProcessOrders_FullMethodName = "/hello.Greeter/processOrders"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// 设置方法
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// 设置服务流rpc
	SearchOrders(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SearchOrdersClient, error)
	// 设置客户流rpc
	UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (Greeter_UpdateOrdersClient, error)
	// 设置双工rpc
	ProcessOrders(ctx context.Context, opts ...grpc.CallOption) (Greeter_ProcessOrdersClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SearchOrders(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SearchOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], Greeter_SearchOrders_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSearchOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SearchOrdersClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSearchOrdersClient struct {
	grpc.ClientStream
}

func (x *greeterSearchOrdersClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) UpdateOrders(ctx context.Context, opts ...grpc.CallOption) (Greeter_UpdateOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], Greeter_UpdateOrders_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterUpdateOrdersClient{stream}
	return x, nil
}

type Greeter_UpdateOrdersClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterUpdateOrdersClient struct {
	grpc.ClientStream
}

func (x *greeterUpdateOrdersClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterUpdateOrdersClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) ProcessOrders(ctx context.Context, opts ...grpc.CallOption) (Greeter_ProcessOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], Greeter_ProcessOrders_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterProcessOrdersClient{stream}
	return x, nil
}

type Greeter_ProcessOrdersClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterProcessOrdersClient struct {
	grpc.ClientStream
}

func (x *greeterProcessOrdersClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterProcessOrdersClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// 设置方法
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// 设置服务流rpc
	SearchOrders(*HelloRequest, Greeter_SearchOrdersServer) error
	// 设置客户流rpc
	UpdateOrders(Greeter_UpdateOrdersServer) error
	// 设置双工rpc
	ProcessOrders(Greeter_ProcessOrdersServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) SearchOrders(*HelloRequest, Greeter_SearchOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchOrders not implemented")
}
func (UnimplementedGreeterServer) UpdateOrders(Greeter_UpdateOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateOrders not implemented")
}
func (UnimplementedGreeterServer) ProcessOrders(Greeter_ProcessOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessOrders not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SearchOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SearchOrders(m, &greeterSearchOrdersServer{stream})
}

type Greeter_SearchOrdersServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSearchOrdersServer struct {
	grpc.ServerStream
}

func (x *greeterSearchOrdersServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_UpdateOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).UpdateOrders(&greeterUpdateOrdersServer{stream})
}

type Greeter_UpdateOrdersServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterUpdateOrdersServer struct {
	grpc.ServerStream
}

func (x *greeterUpdateOrdersServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterUpdateOrdersServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_ProcessOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).ProcessOrders(&greeterProcessOrdersServer{stream})
}

type Greeter_ProcessOrdersServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterProcessOrdersServer struct {
	grpc.ServerStream
}

func (x *greeterProcessOrdersServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterProcessOrdersServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "searchOrders",
			Handler:       _Greeter_SearchOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "updateOrders",
			Handler:       _Greeter_UpdateOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "processOrders",
			Handler:       _Greeter_ProcessOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hello/hello.proto",
}
